trigger: none

pool: 'DevOps Deployment'

variables: 
- template: variables.yml

steps:
- script: curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
  displayName: Install az cli

# Deploy to the data lake
- template: pipeline_generation_template.yml
  parameters:
    environment: 'prod'
    user_assigned_managed_identity_id: $(USER_ASSIGNED_MANAGED_IDENTITY_PROD)
