trigger:
  paths:
    include:
    - pipeline_generation/

pool: 'DevOps Deployment'

variables:
- template: variables.yml 

steps:
# Deploy to Dev
- ${{ if ne(variables['build.sourceBranch'], 'refs/heads/main') }}:
  - template: pipeline_generation_template.yml
    parameters:
      environment: 'dev'
      user_assigned_managed_identity_id: $(USER_ASSIGNED_MANAGED_IDENTITY_DEV)

# Deploy to Test
- ${{ if eq(variables['build.sourceBranch'], 'refs/heads/main') }}:
  - template: pipeline_generation_template.yml
    parameters:
      environment: 'test'
      user_assigned_managed_identity_id: $(USER_ASSIGNED_MANAGED_IDENTITY_TEST)
