trigger:
  paths:
    include:
    - pipeline_generation/

pool: 'Devops Deployment'

variables:
- template: variables.yml 

steps:
- script: curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
  displayName: Install az cli

# Deploy to Dev
- ${{ if ne(variables['build.sourceBranch'], 'refs/heads/main') }}:
  - template: dbt_template.yml
    parameters:
      environment: 'dev'
      user_assigned_managed_identity_id: $(USER_ASSIGNED_MANAGED_IDENTITY_DEV)

# Deploy to Test
- ${{ if eq(variables['build.sourceBranch'], 'refs/heads/main') }}:
  - template: dbt_template.yml
    parameters:
      environment: 'test'
      user_assigned_managed_identity_id: $(USER_ASSIGNED_MANAGED_IDENTITY_TEST)
