trigger: none

pool: 'DevOps Deployment'

variables: 
- template: variables.yml

jobs:
- job: build
  steps:
  - template: pre-processing_template_build.yml

- job: upload
  dependsOn: build
  steps:
  - template: pre-processing_template_prepare.yml

  - template: pre-processing_template_upload.yml
    parameters:
      environment: 'prod'
      user_assigned_managed_identity_id: $(USER_ASSIGNED_MANAGED_IDENTITY_PROD)
